/**
 * Generate a PDF tax report for Skatteverket filing.
 * Uses jsPDF (already in project dependencies).
 */
export async function generateTaxReportPdf(report: {
  host_name: string;
  tax_year: number;
  currency: string;
  properties: Array<{
    property_title: string;
    registration_number?: string | null;
    total_revenue: number;
    total_bookings: number;
    total_nights: number;
    platform_fees: number;
    total_expenses?: number;
    net_income: number;
  }>;
  summary: {
    total_gross_revenue: number;
    total_platform_fees: number;
    total_expenses?: number;
    total_net_income: number;
    total_bookings: number;
    total_nights: number;
  };
  skatteverket: {
    inkomstslag: string;
    schablonavdrag: number;
    taxable_amount: number;
    note: string;
  };
}): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  const fmt = (n: number) => `${Math.round(n).toLocaleString('sv-SE')} SEK`;
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.text('Nordic Getaways — Tax Report', 14, y);
  y += 10;
  doc.setFontSize(11);
  doc.text(`Host: ${report.host_name}`, 14, y);
  y += 6;
  doc.text(`Tax Year: ${report.tax_year}`, 14, y);
  y += 6;
  doc.text(`Generated: ${new Date().toLocaleDateString('sv-SE')}`, 14, y);
  y += 12;

  // Summary
  doc.setFontSize(14);
  doc.text('Summary', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.text(`Gross Revenue: ${fmt(report.summary.total_gross_revenue)}`, 14, y); y += 6;
  doc.text(`Platform Fees: -${fmt(report.summary.total_platform_fees)}`, 14, y); y += 6;
  if (report.summary.total_expenses) {
    doc.text(`Expenses: -${fmt(report.summary.total_expenses)}`, 14, y); y += 6;
  }
  doc.text(`Net Income: ${fmt(report.summary.total_net_income)}`, 14, y); y += 6;
  doc.text(`Total Bookings: ${report.summary.total_bookings}`, 14, y); y += 6;
  doc.text(`Total Nights: ${report.summary.total_nights}`, 14, y); y += 10;

  // Skatteverket
  doc.setFontSize(14);
  doc.text('Skatteverket — Inkomstdeklaration', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.text(`Inkomstslag: ${report.skatteverket.inkomstslag}`, 14, y); y += 6;
  doc.text(`Schablonavdrag: ${fmt(report.skatteverket.schablonavdrag)}`, 14, y); y += 6;
  doc.text(`Taxable Amount: ${fmt(report.skatteverket.taxable_amount)}`, 14, y); y += 6;
  doc.text(`Estimated Tax (30%): ${fmt(report.skatteverket.taxable_amount * 0.3)}`, 14, y); y += 10;

  // Per-property breakdown
  doc.setFontSize(14);
  doc.text('Property Breakdown', 14, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Property', 14, y);
  doc.text('Bookings', 90, y);
  doc.text('Nights', 110, y);
  doc.text('Revenue', 130, y);
  doc.text('Expenses', 155, y);
  doc.text('Net', 180, y);
  y += 6;
  doc.setFont('helvetica', 'normal');

  for (const p of report.properties) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(p.property_title.substring(0, 30), 14, y);
    doc.text(String(p.total_bookings), 90, y);
    doc.text(String(p.total_nights), 110, y);
    doc.text(fmt(p.total_revenue), 130, y);
    doc.text(fmt(p.total_expenses || 0), 155, y);
    doc.text(fmt(p.net_income), 180, y);
    y += 5;
  }

  // Footer
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text('OBS: Detta ar en berakningshjalp — kontrollera alltid mot Skatteverkets aktuella regler.', 14, y);
  doc.text('Generated by Nordic Getaways. Not tax advice.', 14, y + 4);

  doc.save(`nordic-getaways-tax-report-${report.tax_year}.pdf`);
}
