project_id = "bbuutvozqfzbsnllsiai"

[functions.generate-yale-code]
verify_jwt = true

[functions.complete-host-referral]
verify_jwt = true

[functions.fetch-printful-products]
verify_jwt = true

[functions.sync-printful-products]
verify_jwt = true

[functions.create-product-payment]
verify_jwt = false

[functions.create-booking-payment]
verify_jwt = false

[functions.create-booking-payment-connect]
verify_jwt = false

[functions.handle-payment-success]
verify_jwt = false

[functions.create-printful-order]
verify_jwt = false

[functions.create-cart-payment]
verify_jwt = false

[functions.export-ical]
verify_jwt = false

[functions.send-guestbook-invitations]
verify_jwt = false
[functions.sync-ical]
verify_jwt = true

[functions.auto-sync-ical]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.create-connect-dashboard-link]
verify_jwt = true

[functions.send-booking-notifications]
verify_jwt = false

[functions.send-host-invitation]
verify_jwt = true

[functions.handle-shop-payment-success]
verify_jwt = false