project_id = "bbuutvozqfzbsnllsiai"

[functions.fetch-printful-products]
verify_jwt = false

[functions.sync-printful-products]
verify_jwt = false

[functions.create-product-payment]
verify_jwt = false

[functions.create-booking-payment]
verify_jwt = false

[functions.create-booking-payment-connect]
verify_jwt = false

[functions.handle-payment-success]
verify_jwt = false

[functions.create-printful-order]
verify_jwt = false

[functions.create-cart-payment]
verify_jwt = false

[functions.export-ical]
verify_jwt = false

[functions.sync-ical]
verify_jwt = false

[functions.auto-sync-ical]
verify_jwt = false